#spring.datasource.url=jdbc:mysql://localhost:3306/freedom-cms
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#server.port=8080

spring:
  datasource:
    url: jdbc:mysql://192.168.3.35:3306/freedom-cms-new
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    

kaptcha:
  session:
    key: kaptcha.code
  #border: no
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy  
  obscurificator:
    impl: com.google.code.kaptcha.impl.ShadowGimpy
   #不要噪点
  noise:
    impl: com.google.code.kaptcha.impl.NoNoise
  image:
    width: 110
    height: 40
  textproducer:
    font:
      size: 36
      color: green
    char:
      length: 4
      space: 5
  #和登录框背景颜色一致
  background:
    clear:
      from: 247,247,247
      to: 247,247,247
     
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql